"""
LLM-powered hypothesis generator for GEPA reflective evolution.

Replaces the 8 hardcoded hypothesis templates with dynamic,
context-aware hypotheses generated by an LLM (Anthropic Claude)
based on recent experiment logs, agent states, and blind spots.

Usage::

    from dex.llm_hypothesis import LLMHypothesisGenerator

    gen = LLMHypothesisGenerator(api_key="...", model="claude-sonnet-4-6")
    new_hypotheses = gen.generate(
        experiments=engine.experiment_logs[-10:],
        agents=agents,
        blind_spots=engine.blind_spots[-3:],
        n=4,
    )
    engine.inject_hypotheses(new_hypotheses)
"""

from __future__ import annotations

import json
import os
import time
from typing import Any, Dict, List, Optional

import requests

from dex.reflection import Hypothesis

# ---------------------------------------------------------------------------
# Prompt template (Chinese — matches the codebase language)
# ---------------------------------------------------------------------------

SYSTEM_PROMPT = """你是一个加密货币量化交易策略研究助手。你的任务是分析最近的策略实验日志，
发现失败模式，并提出新的、可验证的参数调整假设。

输出格式必须是严格 JSON：
```json
{
  "analysis": "对最近实验的简要分析（1-2句话）",
  "hypotheses": [
    {
      "text": "假设描述（中文，简洁明确）",
      "agent": "Alpha|Beta|Gamma|Delta",
      "param_changes": {"参数名": 新值, ...},
      "rationale": "为什么这个调整可能有效（1-2句话）",
      "blind_spot": "这个假设忽略了什么风险或市场条件"
    }
  ]
}
```

规则：
- 每个假设必须指定 target agent（Alpha/Beta/Gamma/Delta 之一）
- param_changes 中只包含要修改的参数，不需要全部列出
- 参数值必须是具体的数字或布尔值，不能是表达式
- 整数参数（window, atr_period, max_hold_bars, rsi_threshold, adx_threshold, grid_levels, trend_ma_period, rsi_period, rsi_low, rsi_high, ma_period）的值必须是整数
- 连续参数（std_dev, atr_multiplier, entry_zone, grid_spacing_pct, base_size, atr_spacing_mult, max_position, take_profit_pct, stop_loss_pct）可以是小数
- 布尔参数（use_adx, use_macd, use_volume, enable_short, use_resonance 等）必须是 true/false
- 提出 2-4 个不同的假设，针对不同的 agent
- 避免重复已经尝试过的参数组合
- 优先针对表现最差的 agent 提出假设
- 如果多个 agent 都存在类似问题，可以提出跨 agent 的通用假设"""


def build_user_prompt(
    experiments: List[Dict[str, Any]],
    agents: List[Dict[str, Any]],
    blind_spots: List[str],
    market_context: str = "",
) -> str:
    """Build a structured user prompt from recent experiment data.

    Args:
        experiments: List of recent experiment dicts with keys:
            agent, hypothesis, tried, score_before, score_after,
            sharpe_before, sharpe_after, ret_before, ret_after,
            dd_before, dd_after, reflection, edge_flags.
        agents: List of current agent states with keys:
            name, style, params, recent_score, revival_count.
        blind_spots: List of detected blind spots (strings).
        market_context: Optional market regime description.

    Returns:
        Formatted prompt string.
    """
    lines = ["## 当前市场环境", ""]
    if market_context:
        lines.append(market_context)
    else:
        lines.append("未知（未启用市场状态检测）")
    lines.append("")

    # Agent summary
    lines.append("## Agent 当前状态")
    lines.append("")
    lines.append("| Agent | 风格 | 最近评分 | 恢复次数 | 关键参数 |")
    lines.append("|-------|------|----------|----------|----------|")
    for a in agents:
        params_summary = ", ".join(
            f"{k}={v}" for k, v in sorted(a.get("params", {}).items())
            if k in {
                "window", "std_dev", "atr_multiplier", "max_hold_bars",
                "rsi_low", "rsi_high", "rsi_period", "ma_period",
                "entry_zone", "grid_spacing_pct", "grid_levels",
            }
        )
        lines.append(
            f"| {a['name']} | {a.get('style', '?')} | "
            f"{a.get('recent_score', 0):.3f} | {a.get('revival_count', 0)} | "
            f"{params_summary} |"
        )
    lines.append("")

    # Blind spots
    if blind_spots:
        lines.append("## 已发现的盲点")
        lines.append("")
        for bs in blind_spots:
            lines.append(f"- {bs}")
        lines.append("")

    # Experiment history
    lines.append("## 最近实验记录")
    lines.append("")
    for i, exp in enumerate(experiments[-10:], 1):
        lines.append(f"### 实验 {i}: {exp.get('agent', '?')}")
        lines.append(f"- 假设: {exp.get('hypothesis', '?')}")
        lines.append(f"- 参数变化: {exp.get('tried', '?')}")
        lines.append(
            f"- 结果: score {exp.get('score_before', 0):.3f} → "
            f"{exp.get('score_after', 0):.3f} "
            f"({exp.get('score_after', 0) - exp.get('score_before', 0):+.3f}), "
            f"sharpe {exp.get('sharpe_before', 0):.2f} → "
            f"{exp.get('sharpe_after', 0):.2f}, "
            f"DD {exp.get('dd_before', 0)*100:.1f}% → "
            f"{exp.get('dd_after', 0)*100:.1f}%"
        )
        flags = exp.get("edge_flags", [])
        if flags:
            lines.append(f"- 标记: {', '.join(flags)}")
        lines.append(f"- 反思: {exp.get('reflection', '?')[:120]}")
        lines.append("")

    lines.append("请分析以上实验记录，提出 3-4 个新的参数调整假设。")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Hypothesis generator
# ---------------------------------------------------------------------------


class LLMHypothesisGenerator:
    """Generate trading strategy hypotheses using an LLM.

    Supports two backend providers:
        - ``"anthropic"`` — Anthropic Messages API (claude-* models)
        - ``"deepseek"`` — DeepSeek API (OpenAI-compatible, deepseek-chat / deepseek-reasoner)

    Auto-detects provider from model name or ``provider`` parameter.
    Falls back to template hypotheses on API errors or when no API key is configured.

    Attributes:
        api_key: API key for the selected provider.
        provider: ``"anthropic"`` or ``"deepseek"``.
        model: Model ID.
        base_url: API endpoint URL.
        max_retries: Number of retries on API failure.
    """

    # Provider presets
    _PRESETS: Dict[str, Dict[str, str]] = {
        "anthropic": {
            "base_url": "https://api.anthropic.com/v1/messages",
            "env_key": "ANTHROPIC_API_KEY",
        },
        "deepseek": {
            "base_url": "https://api.deepseek.com/v1/chat/completions",
            "env_key": "DEEPSEEK_API_KEY",
        },
    }

    def __init__(
        self,
        api_key: Optional[str] = None,
        model: str = "deepseek-v4-flash",
        provider: str = "auto",
        base_url: Optional[str] = None,
        max_retries: int = 2,
    ):
        # Auto-detect provider
        if provider == "auto":
            if model.startswith("claude-"):
                provider = "anthropic"
            elif model.startswith("deepseek-"):
                provider = "deepseek"
            else:
                provider = "deepseek"  # default: OpenAI-compatible

        self.provider = provider
        self.model = model
        self.max_retries = max_retries
        self._cache: Dict[str, List[Hypothesis]] = {}

        # Resolve API key: explicit arg > env var
        preset = self._PRESETS.get(provider, self._PRESETS["deepseek"])
        if api_key:
            self.api_key = api_key
        else:
            self.api_key = os.environ.get(preset["env_key"], "")
            # Also try generic env vars
            if not self.api_key:
                self.api_key = os.environ.get("LLM_API_KEY", "")

        # Resolve base URL
        if base_url:
            self.base_url = base_url
        else:
            self.base_url = os.environ.get(
                "LLM_BASE_URL", preset["base_url"]
            )

    @property
    def is_available(self) -> bool:
        """Check whether the LLM backend is configured."""
        return bool(self.api_key)

    def generate(
        self,
        experiments: List[Any],
        agents: List[Any],
        blind_spots: Optional[List[str]] = None,
        market_context: str = "",
        n: int = 4,
    ) -> List[Hypothesis]:
        """Generate new hypotheses from recent experiment history.

        Args:
            experiments: List of ExperimentLog objects or dicts.
            agents: List of Agent objects or dicts.
            blind_spots: Detected blind spots (strings).
            market_context: Optional market regime description.
            n: Maximum number of hypotheses to generate.

        Returns:
            List of Hypothesis objects. Empty list on failure.
        """
        if not self.is_available:
            return []

        # Convert experiments to dicts
        exp_dicts = []
        for exp in experiments:
            if hasattr(exp, "__dict__"):
                d = {
                    "agent": getattr(exp, "agent", ""),
                    "hypothesis": getattr(exp, "hypothesis", ""),
                    "tried": getattr(exp, "tried", ""),
                    "score_before": getattr(exp, "score_before", 0.0),
                    "score_after": getattr(exp, "score_after", 0.0),
                    "sharpe_before": getattr(exp, "sharpe_before", 0.0),
                    "sharpe_after": getattr(exp, "sharpe_after", 0.0),
                    "ret_before": getattr(exp, "ret_before", 0.0),
                    "ret_after": getattr(exp, "ret_after", 0.0),
                    "dd_before": getattr(exp, "dd_before", 0.0),
                    "dd_after": getattr(exp, "dd_after", 0.0),
                    "reflection": getattr(exp, "reflection", ""),
                    "edge_flags": getattr(exp, "edge_flags", []),
                }
            elif isinstance(exp, dict):
                d = exp
            else:
                continue
            exp_dicts.append(d)

        # Convert agents to dicts
        agent_dicts = []
        for a in agents:
            if hasattr(a, "name"):
                agent_dicts.append({
                    "name": a.name,
                    "style": getattr(a, "style", ""),
                    "params": getattr(a, "params", {}),
                    "recent_score": a.recent_score() if hasattr(a, "recent_score") else 0.0,
                    "revival_count": getattr(a, "generation", 0),
                })
            elif isinstance(a, dict):
                agent_dicts.append(a)

        # Build prompt
        user_prompt = build_user_prompt(
            exp_dicts, agent_dicts, blind_spots or [], market_context
        )

        # Cache key (hash of the prompt to avoid duplicate calls)
        cache_key = user_prompt[-200:]  # Use tail as simple cache key
        if cache_key in self._cache:
            return self._cache[cache_key]

        # Call LLM with retries
        for attempt in range(self.max_retries + 1):
            try:
                response = self._call_api(user_prompt)
                hypotheses = self._parse_response(response, n)
                if hypotheses:
                    self._cache[cache_key] = hypotheses
                    return hypotheses
                else:
                    print(f"  [LLM] 解析失败：未能从响应中提取有效假设 (尝试 {attempt + 1})")
            except Exception as e:
                print(f"  [LLM] 调用失败 (尝试 {attempt + 1}/{self.max_retries + 1}): {e}")
                if attempt < self.max_retries:
                    time.sleep(2 ** attempt)

        return []

    def _call_api(self, user_prompt: str) -> str:
        """Call the LLM API (dispatches to provider-specific method).

        Args:
            user_prompt: The user message content.

        Returns:
            Raw response text from the assistant.

        Raises:
            requests.RequestException: On HTTP errors.
            ValueError: On unexpected response format.
        """
        if self.provider == "anthropic":
            return self._call_anthropic(user_prompt)
        else:
            return self._call_openai_compatible(user_prompt)

    def _call_anthropic(self, user_prompt: str) -> str:
        """Call Anthropic Messages API."""
        headers = {
            "x-api-key": self.api_key,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json",
        }

        payload: Dict[str, Any] = {
            "model": self.model,
            "max_tokens": 2048,
            "temperature": 0.7,
            "system": SYSTEM_PROMPT,
            "messages": [
                {"role": "user", "content": user_prompt},
            ],
        }

        resp = requests.post(
            self.base_url,
            headers=headers,
            json=payload,
            timeout=120,
        )
        resp.raise_for_status()
        data = resp.json()

        content = data.get("content", [])
        if not content:
            raise ValueError("Empty response content")

        text = ""
        for block in content:
            if block.get("type") == "text":
                text += block.get("text", "")

        if not text:
            raise ValueError("No text in response")
        return text

    def _call_openai_compatible(self, user_prompt: str) -> str:
        """Call OpenAI-compatible Chat Completions API (DeepSeek, etc.)."""
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }

        payload: Dict[str, Any] = {
            "model": self.model,
            "max_tokens": 2048,
            "temperature": 0.7,
            "messages": [
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ],
        }

        print(f"  [LLM] 正在调用 {self.provider}/{self.model} (prompt {len(user_prompt)} chars)...")
        resp = requests.post(
            self.base_url,
            headers=headers,
            json=payload,
            timeout=180,
        )

        if resp.status_code != 200:
            body = resp.text[:500]
            raise requests.RequestException(
                f"HTTP {resp.status_code}: {body}"
            )

        data = resp.json()

        # OpenAI-compatible response format
        choices = data.get("choices", [])
        if not choices:
            raise ValueError(f"Empty choices in response: {json.dumps(data, ensure_ascii=False)[:500]}")

        text = choices[0].get("message", {}).get("content", "")
        if not text:
            raise ValueError("No text in response")
        return text

    def _parse_response(
        self, text: str, n: int = 4
    ) -> List[Hypothesis]:
        """Parse LLM response into Hypothesis objects.

        Args:
            text: Raw LLM response text.
            n: Maximum number of hypotheses to return.

        Returns:
            List of Hypothesis objects.
        """
        # Extract JSON block from markdown code fence
        json_str = text
        if "```json" in text:
            start = text.index("```json") + 7
            end = text.index("```", start)
            json_str = text[start:end].strip()
        elif "```" in text:
            start = text.index("```") + 3
            end = text.index("```", start)
            json_str = text[start:end].strip()

        data = json.loads(json_str)

        if "hypotheses" not in data:
            return []

        hypotheses = []
        # Valid agent names
        valid_agents = {"Alpha", "Beta", "Gamma", "Delta"}

        for h_data in data["hypotheses"][:n]:
            agent = h_data.get("agent", "Alpha")
            if agent not in valid_agents:
                agent = "Alpha"

            # Clean param_changes: ensure values are concrete
            params = {}
            for k, v in h_data.get("param_changes", {}).items():
                if isinstance(v, bool):
                    params[k] = v
                elif isinstance(v, str):
                    # Try to convert string numbers
                    try:
                        params[k] = float(v)
                        if params[k] == int(params[k]):
                            params[k] = int(params[k])
                    except ValueError:
                        params[k] = v
                elif isinstance(v, (int, float)):
                    params[k] = v
                else:
                    continue

            hypotheses.append(Hypothesis(
                text=h_data.get("text", ""),
                agent=agent,
                param_changes=params,
                rationale=h_data.get("rationale", ""),
                blind_spot=h_data.get("blind_spot", ""),
            ))

        return hypotheses


# ---------------------------------------------------------------------------
# Convenience: inject LLM hypotheses into ReflectionEngine
# ---------------------------------------------------------------------------


def inject_llm_hypotheses(
    engine: Any,  # ReflectionEngine
    generator: LLMHypothesisGenerator,
    experiments: List[Any],
    agents: List[Any],
    blind_spots: Optional[List[str]] = None,
    n: int = 4,
) -> int:
    """Generate and inject LLM hypotheses into a ReflectionEngine.

    Args:
        engine: ReflectionEngine instance.
        generator: LLMHypothesisGenerator instance.
        experiments: Recent experiment logs.
        agents: Current agent list.
        blind_spots: Detected blind spots.
        n: Number of hypotheses to generate.

    Returns:
        Number of hypotheses injected (0 if LLM unavailable or failed).
    """
    new_h = generator.generate(
        experiments=experiments[-10:],
        agents=agents,
        blind_spots=blind_spots or [],
        n=n,
    )

    if new_h:
        engine.inject_hypotheses(new_h)
        print(f"  [LLM] 注入了 {len(new_h)} 条新假设:")
        for h in new_h:
            print(f"    - [{h.agent}] {h.text[:80]}...")

    return len(new_h)
